ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:${ELK_VERSION}

EXPOSE 5601
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
