ARG ELK_VERSION=7.5.1

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

EXPOSE 9200 9300
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
